# Generated by Django 4.1.7 on 2024-05-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
