# Generated by Django 4.1.7 on 2024-05-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_courses_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
