# Generated by Django 4.1.7 on 2024-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_courses_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
