# Generated by Django 4.1.7 on 2024-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('contactNumber', models.IntegerField()),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
