# Generated by Django 4.1.7 on 2024-05-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contactNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
