# Generated by Django 4.1.7 on 2024-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_alter_contactus_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contactAddress',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
