# Generated by Django 4.1.7 on 2024-06-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_contactus_contactaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-sent_date',)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(default=1),
        ),
    ]
