# Generated by Django 4.1.7 on 2024-06-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_remove_comments_name_comments_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-comment_date']},
        ),
    ]
