# Generated by Django 4.1.7 on 2024-06-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_profile_country_profile_courses_enroll_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='city',
        ),
    ]
