# Generated by Django 4.1.7 on 2024-06-15 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0017_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ('created', 'updated')},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(related_name='course_enrollment', to='Base.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
