# Generated by Django 4.1.7 on 2024-06-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0018_alter_courses_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
