# Generated by Django 4.1.7 on 2024-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0020_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=300)),
                ('member_description', models.TextField()),
                ('facebook_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('histogram_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
