# Generated by Django 4.1.7 on 2024-06-16 10:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0021_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='TeamImages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
            preserve_default=False,
        ),
    ]
