# Generated by Django 4.1.7 on 2024-06-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0022_team_team_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_img',
            new_name='member_img',
        ),
    ]
