# Generated by Django 4.1.7 on 2024-06-17 07:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0023_rename_team_img_team_member_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='Course_Videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_img',
            field=models.ImageField(blank=True, null=True, upload_to='CourseImage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
